# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1a7fc7b494c0d71a2bdf8c0a73b7b50e"
name = "shipvolume"
handle = "shipvolume"
application_url = "https://seemed-disclose-wa-funky.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shoppiapps.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = ["https://seemed-disclose-wa-funky.trycloudflare.com/auth/callback", "https://seemed-disclose-wa-funky.trycloudflare.com/auth/shopify/callback", "https://seemed-disclose-wa-funky.trycloudflare.com/api/auth/callback"]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
